image:
  repository: pnda/platform-deployment-manager
  tag: release5.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

conf:
  logLevel: INFO

resources:
  requests:
    memory: "128Mi"
    cpu: "10m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
