apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deployment-manager.fullname" . }}-config
  labels:
    app: {{ include "deployment-manager.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  dm-config.json: |-
{{ tpl (.Files.Get "resources/config/dm-config.json") . | indent 4 }}
