apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deployment-manager.fullname" . }}
  labels:
    app: {{ include "deployment-manager.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "deployment-manager.name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ include "deployment-manager.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "deployment-manager.name" . }}
        chart: {{ include "deployment-manager.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ include "deployment-manager.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            - name: REDIS
              value: redis://redis-master
          command:
            - "python3"
            - "app.py"
          volumeMounts:
            - mountPath: /deployment-manager/dm-config.json
              subPath: dm-config.json
              name: deployment-manager-config
      volumes:
        - name: deployment-manager-config
          configMap:
            name: {{ include "deployment-manager.fullname" . }}-config
