apiVersion: v1
kind: Service
metadata:
  name: {{ template "deployment-manager.fullname" . }}
  labels:
    app: {{ template "deployment-manager.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "deployment-manager.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: 5000
      targetPort: 5000
