apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "console-frontend.fullname" . }}-config
  labels:
    app: {{ include "console-frontend.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  PNDA.json: |-
{{ tpl (.Files.Get "resources/config/PNDA.json") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "console-frontend.fullname" . }}-nginx-config
  labels:
    app: {{ include "console-frontend.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  PNDA-nginx.conf: |-
{{ tpl (.Files.Get "resources/config/PNDA-nginx.conf") . | indent 4 }}
