{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "console-frontend.fullname" . }}
  labels:
    app: {{ template "console-frontend.name" . }}
    chart: {{ template "console-frontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: pnda-console-frontend
              servicePort: 80
    {{- end }}
status:
  loadBalancer: {}
{{- end }}
