{{- if .Values.prometheus.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name}}-kafka-metrics
  labels:
    monitoring: prometheus
spec: 
  selector: 
    app: {{ template "cp-kafka.name" . }}
    release: {{ .Release.Name }}
  ports:
  - port: {{ .Values.prometheus.port }}
    name: metrics
    targetPort: {{ .Values.prometheus.port }}
{{- end -}}