{
 "title": "PNDA Main",
 "tags": [ "pnda" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod_node_exporter",
    "query": "label_values(node_boot_time_seconds{job=\"node-exporter\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "# Welcome to PNDA Monitoring Dashboard\n\nSelect component in the up-right corner"
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum by (cpu) (irate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\", pod=\"$pod_node_exporter\"}[2m]))) * 100\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_memory_MemTotal_bytes{job=\"node-exporter\", pod=\"$pod_node_exporter\"}\n    - node_memory_MemFree_bytes{job=\"node-exporter\", pod=\"$pod_node_exporter\"}\n    - node_memory_Buffers_bytes{job=\"node-exporter\", pod=\"$pod_node_exporter\"}\n    - node_memory_Cached_bytes{job=\"node-exporter\", pod=\"$pod_node_exporter\"}\n    )\n    / node_memory_MemTotal_bytes{job=\"node-exporter\", pod=\"$pod_node_exporter\"}\n  ) * 100)\n"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{pod=~\"$pod_node_exporter\",job=~\"node-exporter\"} - node_memory_SwapFree_bytes{pod=~\"$pod_node_exporter\",job=~\"node-exporter\"}) / (node_memory_SwapTotal_bytes{pod=~\"$pod_node_exporter\",job=~\"node-exporter\"} )) * 100"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{pod=~\"$pod_node_exporter\",job=~\"node-exporter\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{pod=~\"$pod_node_exporter\",job=~\"node-exporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{pod=~\"$pod_node_exporter\",job=~\"node-exporter\"}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",pod=~\"$pod_node_exporter\",job=~\"node-exporter\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',pod=~\"$pod_node_exporter\",job=~\"node-exporter\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',pod=~\"$pod_node_exporter\",job=~\"node-exporter\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",pod=~\"$pod_node_exporter\",job=~\"node-exporter\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',pod=~\"$pod_node_exporter\",job=~\"node-exporter\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',pod=~\"$pod_node_exporter\",job=~\"node-exporter\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", pod=\"$pod_node_exporter\"}\n  - node_memory_MemFree_bytes{job=\"node-exporter\", pod=\"$pod_node_exporter\"}\n  - node_memory_Buffers_bytes{job=\"node-exporter\", pod=\"$pod_node_exporter\"}\n  - node_memory_Cached_bytes{job=\"node-exporter\", pod=\"$pod_node_exporter\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "max(node_memory_Buffers_bytes{job=\"node-exporter\", pod=\"$pod_node_exporter\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "max(node_memory_Cached_bytes{job=\"node-exporter\", pod=\"$pod_node_exporter\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "max(node_memory_MemFree_bytes{job=\"node-exporter\", pod=\"$pod_node_exporter\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "node:node_filesystem_usage:\n", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=\"node-exporter\", pod=\"$pod_node_exporter\", device!~\"lo\"}[5m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Usage Per Core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (cpu) (irate(node_cpu_seconds_total{mode!=\"idle\", pod=\"$pod_node_exporter\"}[5m])) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  }
 ]
}