{
 "title": "PNDA Spark",
 "tags": [ "pnda" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod_spark",
    "query": "label_values(jvm_pools_Code_Cache_committed{job=\"spark-standalone-exporter\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_heap_init{pod=\"$pod_spark\"}\n",
     "legendFormat": "initial heap"
    },
    {
     "expr": "jvm_heap_max{pod=\"$pod_spark\"}",
     "legendFormat": "max heap"
    },
    {
     "expr": "jvm_heap_committed{pod=\"$pod_spark\"}",
     "legendFormat": "committed heap"
    },
    {
     "expr": "jvm_heap_used{pod=\"$pod_spark\"}",
     "legendFormat": "used heap"
    }
   ]
  },
  {
   "title": "Non Heap Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_non_heap_init{pod=\"$pod_spark\"}\n",
     "legendFormat": "initial heap"
    },
    {
     "expr": "jvm_non_heap_max{pod=\"$pod_spark\"}",
     "legendFormat": "max heap"
    },
    {
     "expr": "jvm_non_heap_committed{pod=\"$pod_spark\"}",
     "legendFormat": "committed heap"
    },
    {
     "expr": "jvm_non_heap_used{pod=\"$pod_spark\"}",
     "legendFormat": "used heap"
    }
   ]
  },
  {
   "title": "Memory Pool CodeCache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_pools_Code_Cache_committed{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_pools_Code_Cache_used{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_pools_Code_Cache_init{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Init"
    },
    {
     "expr": "jvm_pools_Code_Cache_max{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Memory Pool EdenSpace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_pools_Eden_Space_committed{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_pools_Eden_Space_used{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_pools_Eden_Space_init{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Init"
    },
    {
     "expr": "jvm_pools_Eden_Space_max{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Memory Pool Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_pools_Metaspace_committed{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_pools_Metaspace_used{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_pools_Metaspace_init{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Init"
    },
    {
     "expr": "jvm_pools_Metaspace_max{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Memory Pool SurvivorSpace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_pools_Survivor_Space_committed{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_pools_Survivor_Space_used{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_pools_Survivor_Space_init{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Init"
    },
    {
     "expr": "jvm_pools_Survivor_Space_max{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Memory Pool TenuredGen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_pools_Tenured_Gen_committed{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_pools_Tenured_Gen_used{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_pools_Tenured_Gen_init{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Init"
    },
    {
     "expr": "jvm_pools_Tenured_Gen_max{endpoint=\"metrics\",pod=\"$pod_spark\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Total Workers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(master_workers{pod=\"$pod_spark\"})"
    }
   ]
  },
  {
   "title": "Total Alive Workers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(master_aliveWorkers)\n" }
   ]
  },
  {
   "title": "Total Apps",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(master_apps)\n" }
   ]
  },
  {
   "title": "Total Waiting Apps",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(master_waitingApps)\n" }
   ]
  }
 ]
}