{
 "title": "PNDA hdfs",
 "tags": [ "pnda" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod_hdfs",
    "query": "label_values(jvm_memory_bytes_init{service=\"pnda-hdfs-namenode-metrics\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "HDFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_init{area=\"heap\",endpoint=\"metrics\",pod=\"$pod_hdfs\"}\n",
     "legendFormat": "initial heap"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",endpoint=\"metrics\",pod=\"$pod_hdfs\"}",
     "legendFormat": "max heap"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\",endpoint=\"metrics\",pod=\"$pod_hdfs\"}",
     "legendFormat": "committed heap"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",endpoint=\"metrics\",pod=\"$pod_hdfs\"}",
     "legendFormat": "used heap"
    }
   ]
  },
  {
   "title": "Non Heap Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_init{area=\"nonheap\",endpoint=\"metrics\",pod=\"$pod_hdfs\"}\n",
     "legendFormat": "initial nonheap"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"nonheap\",endpoint=\"metrics\",pod=\"$pod_hdfs\"}",
     "legendFormat": "max nonheap"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\",endpoint=\"metrics\",pod=\"$pod_hdfs\"}",
     "legendFormat": "committed nonheap"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",endpoint=\"metrics\",pod=\"$pod_hdfs\"}",
     "legendFormat": "used nonheap"
    }
   ]
  },
  {
   "title": "Code Cache Pool Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_init{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"Code Cache\"}",
     "legendFormat": "initial"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"Code Cache\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"Code Cache\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"Code Cache\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Metaspace Pool Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_init{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"Metaspace\"}",
     "legendFormat": "initial"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"Metaspace\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"Metaspace\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"Metaspace\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Compressed Class Space Pool Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_init{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"Compressed Class Space\"}",
     "legendFormat": "initial"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"Compressed Class Space\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"Compressed Class Space\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"Compressed Class Space\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Eden Space Pool Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_init{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"G1 Eden Space\"}",
     "legendFormat": "initial"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"G1 Eden Space\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"G1 Eden Space\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"G1 Eden Space\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Survivor Space Pool Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_init{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"G1 Survivor Space\"}",
     "legendFormat": "initial"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"G1 Survivor Space\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"G1 Survivor Space\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"G1 Survivor Space\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Old Gen Pool Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_init{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"G1 Old Gen\"}",
     "legendFormat": "initial"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"G1 Old Gen\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"G1 Old Gen\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{endpoint=\"metrics\",pod=\"$pod_hdfs\",pool=\"G1 Old Gen\"}",
     "legendFormat": "used"
    }
   ]
  }
 ]
}