{
 "title": "PNDA Kafka",
 "tags": [ "pnda" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": "label_values(kafka_log_logstartoffset,topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "$topic topic",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_log_logstartoffset{ topic = \"$topic\" }) - sum(kafka_log_logstartoffset{ topic = \"$topic\" })"
    }
   ]
  },
  {
   "title": "Kafka Broker Uptime",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "java_lang_runtime_uptime{service=\"pnda-kafka-metrics\"}",
     "legendFormat": "Broker {{pod}}"
    }
   ]
  },
  {
   "title": "Topic BytesIn to BytesOut Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\",topic=\"\"}",
     "legendFormat": "BytesInPerSec"
    },
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\",topic=\"\"}",
     "legendFormat": "BytesOutPerSec"
    }
   ]
  },
  {
   "title": "Network Processor Idle (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_processor_idlepercent{service=\"pnda-kafka-metrics\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{service=\"pnda-kafka-metrics\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "JVM System CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{service=\"pnda-kafka-metrics\"}"
    }
   ]
  },
  {
   "title": "Request Handler Idle (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_oneminuterate{service=\"pnda-kafka-metrics\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Kafka Network Request Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_requestmetrics_oneminuterate{service=\"pnda-kafka-metrics\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Total Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount)"
    }
   ]
  },
  {
   "title": "Total Under Replicated Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)"
    }
   ]
  },
  {
   "title": "Max lag in messages btw follower and leader replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicafetchermanager_maxlag",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}