{
 "title": "PNDA hbase",
 "tags": [ "pnda" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod_hbase_master",
    "query": "label_values(hadoop_hbase_responsesize_median{name=\"Master\"}, pod)"
   },
   {
    "name": "pod_hbase_region",
    "query": "label_values(hadoop_hbase_responsesize_median{name=\"RegionServer\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Process Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_processcpuload{endpoint=\"metrics\",pod=\"$pod_hbase_master\"}\n",
     "legendFormat": "master process"
    },
    {
     "expr": "java_lang_operatingsystem_processcpuload{endpoint=\"metrics\",pod=\"$pod_hbase_region\"}",
     "legendFormat": "region process"
    }
   ]
  },
  {
   "title": "CPU System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{endpoint=\"metrics\",pod=\"$pod_hbase_master\"}",
     "legendFormat": "master system"
    },
    {
     "expr": "java_lang_operatingsystem_systemcpuload{endpoint=\"metrics\",pod=\"$pod_hbase_region\"}",
     "legendFormat": "region system"
    }
   ]
  },
  {
   "title": "CPU Current Thread Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_threading_currentthreadcputime{endpoint=\"metrics\",pod=\"$pod_hbase_master\"}",
     "legendFormat": "master thread"
    },
    {
     "expr": "java_lang_threading_currentthreadcputime{endpoint=\"metrics\",pod=\"$pod_hbase_region\"}",
     "legendFormat": "region thread"
    }
   ]
  },
  {
   "title": "Total Info Logs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(hadoop_hbase_loginfo)\n" }
   ]
  },
  {
   "title": "Total Warnings Logs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(hadoop_hbase_logwarn)" }
   ]
  },
  {
   "title": "Total Error Logs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(hadoop_hbase_logerror)" }
   ]
  },
  {
   "title": "Total Fatal Logs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(hadoop_hbase_logfatal)" }
   ]
  },
  {
   "title": "Memory Pool CodeCache MASTER",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memorypool_usage_committed{endpoint=\"metrics\",pod=\"$pod_hbase_master\",name=\"Code Cache\",namespace=\"pnda\",pod=\"pnda-hbase-master-0\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_memorypool_usage_used{endpoint=\"metrics\",pod=\"$pod_hbase_master\",name=\"Code Cache\",namespace=\"pnda\",pod=\"pnda-hbase-master-0\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "java_lang_memorypool_usage_init{endpoint=\"metrics\",pod=\"$pod_hbase_master\",name=\"Code Cache\",namespace=\"pnda\",pod=\"pnda-hbase-master-0\"}",
     "legendFormat": "Init"
    },
    {
     "expr": "java_lang_memorypool_usage_max{endpoint=\"metrics\",pod=\"$pod_hbase_master\",name=\"Code Cache\",namespace=\"pnda\",pod=\"pnda-hbase-master-0\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Memory Pool CodeCache REGION",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memorypool_usage_committed{endpoint=\"metrics\",pod=\"$pod_hbase_region\",name=\"Code Cache\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_memorypool_usage_used{endpoint=\"metrics\",pod=\"$pod_hbase_region\",name=\"Code Cache\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "java_lang_memorypool_usage_init{endpoint=\"metrics\",pod=\"$pod_hbase_region\",name=\"Code Cache\"}",
     "legendFormat": "Init"
    },
    {
     "expr": "java_lang_memorypool_usage_max{endpoint=\"metrics\",pod=\"$pod_hbase_region\",name=\"Code Cache\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Memory Pool Metaspace MASTER",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memorypool_usage_committed{endpoint=\"metrics\",pod=\"$pod_hbase_master\",name=\"Metaspace\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_memorypool_usage_used{endpoint=\"metrics\",pod=\"$pod_hbase_master\",name=\"Metaspace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "java_lang_memorypool_usage_init{endpoint=\"metrics\",pod=\"$pod_hbase_master\",name=\"Metaspace\"}",
     "legendFormat": "Init"
    },
    {
     "expr": "java_lang_memorypool_usage_max{endpoint=\"metrics\",pod=\"$pod_hbase_master\",name=\"Metaspace\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Memory Pool Metaspace REGION",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memorypool_usage_committed{endpoint=\"metrics\",pod=\"$pod_hbase_region\",name=\"Metaspace\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_memorypool_usage_used{endpoint=\"metrics\",pod=\"$pod_hbase_region\",name=\"Metaspace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "java_lang_memorypool_usage_init{endpoint=\"metrics\",pod=\"$pod_hbase_region\",name=\"Metaspace\"}",
     "legendFormat": "Init"
    },
    {
     "expr": "java_lang_memorypool_usage_max{endpoint=\"metrics\",pod=\"$pod_hbase_region\",name=\"Metaspace\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Memory Pool OldGen MASTER",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memorypool_usage_committed{pod=\"$pod_hbase_master\",name=\"CMS Old Gen\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_memorypool_usage_used{endpoint=\"metrics\",pod=\"$pod_hbase_master\",name=\"PS Old Gen\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "java_lang_memorypool_usage_init{endpoint=\"metrics\",pod=\"$pod_hbase_master\",name=\"PS Old Gen\"}",
     "legendFormat": "Init"
    },
    {
     "expr": "java_lang_memorypool_usage_max{endpoint=\"metrics\",pod=\"$pod_hbase_master\",name=\"PS Old Gen\"}",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}