{{- if .Values.master.prometheus.exporter.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: spark-standalone-exporter
  namespace: pnda
  labels:
    monitoring: prometheus
spec: 
  selector:
    app: {{ template "spark.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.master.prometheus.exporter.port }}
      name: metrics
{{- end }}
