apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ include "hbase.fullname" . }}-regionserver
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/hbase-configmap.yaml") . | sha256sum }}
  labels:
    app: {{ include "hbase.name" . }}
    chart: {{ include "hbase.chart" . }}
    release: {{ .Release.Name }}
    component: regionserver
spec:
  serviceName: {{ include "hbase.fullname" . }}-regionserver
  replicas: {{ .Values.hbase.regionServer.replicas }}
  template:
    metadata:
      labels:
        app: {{ include "hbase.name" . }}
        release: {{ .Release.Name }}
        component: regionserver
    spec:
      affinity:
        podAntiAffinity:
        {{- if eq .Values.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ include "hbase.name" . }}
                release: {{ .Release.Name | quote }}
                component: regionserver
        {{- else if eq .Values.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  {{ include "hbase.name" . }}
                  release: {{ .Release.Name | quote }}
                  component: regionserver
        {{- end }}
      terminationGracePeriodSeconds: 0
      {{- if .Values.prometheus.enabled }}      
      initContainers:
      - name: inject-exporter-jar
        image: "{{ .Values.prometheus.image }}:{{ .Values.prometheus.imageTag }}"
        env:
        - name: SHARED_VOLUME_PATH
          value: /jmx-exporter
        volumeMounts:
        - mountPath: /jmx-exporter
          name: jmx-exporter
      {{- end }}    
      containers:
      - name: regionserver
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
           - "/bin/bash"
           - "/tmp/hbase-config/bootstrap.sh"
           - "-d"
        resources:
{{ toYaml .Values.hbase.regionServer.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /
            port: 16030
          initialDelaySeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 16030
          initialDelaySeconds: 10
          timeoutSeconds: 2
        volumeMounts:
        - name: hbase-config
          mountPath: /tmp/hbase-config
        {{- if .Values.prometheus.enabled }}      
        - name: jmx-exporter  
          mountPath: /jmx-exporter
        - name: exporter-config
          mountPath: /etc/exporter
        {{- end }}
      volumes:
      - name: hbase-config
        configMap:
          name: {{ .Release.Name }}-hbase
      {{- if .Values.prometheus.enabled  }}
      - name: jmx-exporter
        emptyDir: {}      
      - name: exporter-config
        configMap:
          name: {{ template "hbase.fullname" . }}-exporter-configmap
      {{- end }}
