{{- if .Values.platformTesting.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pnda.platform-testing.name" . }}
  labels:
    {{- include "pnda.platform-testing.labels" . | nindent 4 }}
data:
  logging.conf: |-
    [loggers]
    keys=root

    [handlers]
    keys=consoleHandler

    [formatters]
    keys=TestbotMonitor

    [logger_root]
    level={{ .Values.platformTesting.conf.logLevel }}
    handlers=consoleHandler

    [handler_consoleHandler]
    class=StreamHandler
    level={{ .Values.platformTesting.conf.logLevel }}
    formatter=TestbotMonitor
    args=(sys.stdout,)

    [formatter_TestbotMonitor]
    format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
    datefmt=
{{- end -}}