apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "packageRepository.fullname" . }}-config
  labels:
    app: {{ include "packageRepository.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pr-config.json: |
    {
    "FsRepository": {
        "location": {
            "path": "/packages"
        }
    },
    "config": {
        "log_level":"{{ .Values.conf.logLevel }}",
        "package_callback": "http://{{.Release.Name}}-console-backend-data-logger:3001/packages"
    }
    }

