dependencies:
- name: cp-helm-charts
  version: 0.1.0
  repository: "https://confluentinc.github.io/cp-helm-charts/"
  alias: confluent-platform
- name: kafka-manager
  version: 1.1.3
  repository: "https://kubernetes-charts.storage.googleapis.com/"
  condition: kafka-manager.enabled
- name: jupyterhub
  version: 0.8.2
  repository: "https://jupyterhub.github.io/helm-chart/"
  condition: jupyterhub.enabled
- name: spark-standalone
  version: 0.1.0
  repository: file://../spark-standalone
  condition: spark-standalone.enabled
- name: hdfs
  version: 0.1.0
  repository: file://../hdfs
  condition: hdfs.enabled
- name: hbase
  version: 0.1.0
  repository: file://../hbase
  condition: hbase.enabled
- name: opentsdb
  version: 0.1.0
  repository: file://../opentsdb
  condition: opentsdb.enabled
- name: grafana
  version: 3.2.0
  repository: "https://kubernetes-charts.storage.googleapis.com/"
  condition: grafana.enabled
- name: package-repository
  version: 0.1.0
  repository: file://./package-repository
- name: deployment-manager
  version: 0.1.0
  repository: file://./deployment-manager
