{{- if .Values.persistence.nameNode.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "hdfs.fullname" . }}-namenode
  labels:
    app: {{ include "hdfs.name" . }}
    chart: {{ include "hdfs.chart" . }}
    release: {{ .Release.Name }}
    component: namenode
spec:
  accessModes:
  - {{ .Values.persistence.nameNode.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.nameNode.size | quote }}
{{- if .Values.persistence.nameNode.storageClass }}
{{- if (eq "-" .Values.persistence.nameNode.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.nameNode.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
