apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "console-backend-data-logger.fullname" . }}
  labels:
    app: {{ template "console-backend-data-logger.name" . }}
    chart: {{ template "console-backend-data-logger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "console-backend-data-logger.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "console-backend-data-logger.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: REDIS
              value: redis://{{.Release.Name}}-redis-master
          command:
            - "node"
            - "app.js"
