replicaCount: 1

image:
  repository: gradiant/jmxproxy
  tag: 3.4.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
