apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-service.fullname" . }}-config
  labels:
    app: {{ include "data-service.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  server.conf: |-
{{ tpl (.Files.Get "resources/config/server.conf") . | indent 4 }}
