apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-service.fullname" . }}
  labels:
    app: {{ include "data-service.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "data-service.name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ include "data-service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "data-service.name" . }}
        chart: {{ include "data-service.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ include "data-service.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - "python"
            - "apiserver.py"
          volumeMounts:
            - mountPath: /data-service/server.conf
              subPath: server.conf
              name: data-service-config
      volumes:
        - name: data-service-config
          configMap:
            name: {{ include "data-service.fullname" . }}-config
