apiVersion: v1
kind: Service
metadata:
  name: {{ template "data-service.fullname" . }}
  labels:
    app: {{ template "data-service.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "data-service.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
