#to enable singleuser hostname.subdomain kubernetes DNS entry to be resolved from spark executors.
#https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields
apiVersion: v1
kind: Service
metadata:
  name: hub-subdomain
  labels:
    app: jupyterhub
    component: subdomain-service
    release: {{ .Release.Name }}
spec:
  selector:
    app: jupyterhub
    component: singleuser-server
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234