apiVersion: v1
kind: Service
metadata:
  name: {{ include "pnda.data-service.name" . }}
  labels:
    {{- include "pnda.data-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pnda.data-service.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.dataService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
