apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.namespace }}
  labels:
    app: pnda
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.roleName }}
  namespace: {{ .Release.namespace }}
  labels:
    app: pnda
rules:
  # TODO check what resources must be granted
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["services"]
    verbs: ["get","watch","create","list","delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["configmaps"]
    verbs: ["get","watch","create","list","delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["events"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.roleBindingName }}
  namespace: {{ .Release.namespace }}
  labels:
    app: pnda
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.roleName }}
  apiGroup: rbac.authorization.k8s.io
