apiVersion: v1
kind: Service
metadata:
  name: spark-standalone
  labels:
    app: {{ template "spark.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.master.ui_port }}
      name: gui
    - port: {{ .Values.master.port }}
      name: spark
  selector:
    app: {{ template "spark.name" . }}
    release: {{ .Release.Name }}