apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "spark.fullname" . }}-workers
  labels:
    app: {{ template "spark.name" . }}
    chart: {{ template "spark.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  serviceName: {{ template "spark.fullname" . }}-workers
  selector:
    matchLabels:
      app: {{ template "spark.name" . }}-worker
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "spark.name" . }}-worker
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: {{ template "spark.fullname" . }}-worker
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        {{- range $key, $value := .Values.master.customEnv }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        args:
        - standalone
        - worker
        - spark://{{ template "spark.fullname" . }}:7077
        - --webui-port {{ .Values.worker.ui_port }}

      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
