# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.fullname" . }}-datanode
  labels:
    app: {{ include "hdfs.name" . }}
    chart: {{ include "hdfs.chart" . }}
    release: {{ .Release.Name }}
    component: datanode
spec:
  ports:
  - name: dfs
    port: 9000
    protocol: TCP
  - name: webhdfs
    port: 50075
  clusterIP: None
  selector:
    app: {{ include "hdfs.name" . }}
    release: {{ .Release.Name }}
    component: datanode
