{{- if .Values.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opentsdb.fullname" . }}-nodeport
  labels:
    app: {{ include "opentsdb.name" . }}
    chart: {{ include "opentsdb.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - name: external-daemon
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      nodePort: {{ .Values.nodePort.externalPort }}
      protocol: TCP
  selector:
    app: {{ include "opentsdb.name" . }}
    release: {{ .Release.Name }}
{{- end }}
