apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentsdb.fullname" . }}-init
  labels:
    app: {{ include "opentsdb.name" . }}
    chart: {{ include "opentsdb.chart" . }}
    release: {{ .Release.Name }}
data:
  create_hbase_tables.sh: |-
{{ tpl (.Files.Get "resources/config/create_hbase_tables.sh") . | indent 4 }}