apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "console-backend-data-manager.fullname" . }}-config
  labels:
    app: {{ include "console-backend-data-manager.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.js: |-
{{ tpl (.Files.Get "resources/config/data-manager-config.js") . | indent 4 }}
