apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "console-backend-data-manager.fullname" . }}
  labels:
    app: {{ template "console-backend-data-manager.name" . }}
    chart: {{ template "console-backend-data-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "console-backend-data-manager.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "console-backend-data-manager.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS
              value: redis://redis-master
          command:
            - "node"
            - "app.js"
          volumeMounts:
            - mountPath: /console-backend-data-manager/conf/config.js
              subPath: config.js
              name: data-manager-config
      volumes:
        - name: data-manager-config
          configMap:
            name: {{ template "console-backend-data-manager.fullname" . }}-config
