apiVersion: v1
kind: Service
metadata:
  name: {{ include "pnda.console-frontend.name" . }}
  labels:
    {{- include "pnda.console-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.consoleFrontend.service.type }}
  ports:
    - port: {{ .Values.consoleFrontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pnda.console-frontend.labels" . | nindent 4 }}
